#!/usr/bin/env python3.7

# A program that runs thermoclass for a batch of
# PDB files retrieved from a multiple FASTA
# file.

import sys
import os
from data_process import run_blastp
from data_process import parse_blastp_results

fasta = sys.argv[1]
#result_files = run_blastp(fasta)

result_files = ['XML/trivial_multiple_case-0.xml', 'XML/trivial_multiple_case-1.xml']

pdb_ids = parse_blastp_results(result_files)

for pdb_id in pdb_ids:
	cline = "./thermoclass -p {0} -g --per_tok -n ".format(pdb_id)+\
			"emb/{0}_per_tok.npz -o".format(pdb_id)+\
			"predictions/{0}_per_tok_predictions -e emb/".format(pdb_id)
	os.system(cline)
