#!/usr/bin/env python3.7

# A program that runs thermoclass for a batch of
# PDB IDs

import sys
import os

pdb_ids = sys.argv[1:]

for pdb_id in pdb_ids:
	pdb_id = pdb_id.lower()
	print("Running thermoclass for "+pdb_id)
	cline = "./thermoclass -p {0} -g --per_tok -n ".format(pdb_id)+\
			"emb/{0}_per_tok.npz -o".format(pdb_id)+\
			"predictions/TSV/{0}_per_tok -e emb/".format(pdb_id)
	os.system(cline)

